### PR TITLE
Change graphic element height dynamically to accomodate browser chrome changes

### PR DESCRIPTION
**Pull request by drzax**

### CODE REVIEW

**Review by phocks — APPROVED** [review]
Interesting fix!

**Comment by drzax** [comment]
If you think there are any better options, I'm all ears, @phocks .

**Comment by phocks** [comment]
Tomorrow I'll have a look at this in action but yeah seems interesting. Is this just to deal with in app height? Or does it address height changes on mobile browsers too? I've had to do things like forcibly ignore smaller window height changes on mobile etc to deal with the search bar and browser chrome coming in and out. Not sure what the optimal solution is. I think I'd prefer if browsers didn't constantly alter their window.innerHeight when they changed scroll direction.

**Comment by drzax** [comment]
It deals with the browser chrome changes for sure and I'm hopeful it also fixes the same issue in the app. It will likely necessitate dealing with a changing container size in scrollyteller graphics, but since that's just part of being responsive, which we pretty much already are all the time, it shouldn't be a huge burden. 

It's annoying that mobile browsers do that, but not sure there's much we can do about that.

**Pull request merged**
