### PR TITLE
4.0 release candidate

### PR DESCRIPTION
**Pull request by drzax**
- Create a shared graphic component for the examples
- Tighter type definitions
- Better separation between CM utils and the component
- Return more data from the onProgress hook
- Support for theme, waypoint and graphicinfront config from CM tags
- Better separation between config and data on the #marks
- Update examples
- Update readme

### CODE REVIEW

**Review by phocks — APPROVED** [review]
Looks pretty good to me

**Comment by drzax** [comment]
Going to merge this and release 4.0 today unless I hear any objections.

**Comment by phocks** [comment]
What happened to version 3?

**Comment by drzax** [comment]
There's already a version 3 on npm. Not sure why it's not listed under
releases here.

**Pull request merged**
